pimcore:
    staticroutes:
        definitions:
            d0cf1798-bc5a-45bc-99e2-24818a4cbdca:
                name: product-info
                pattern: '/\/product-info\/([^]+)([0-9]+)'
                reverse: /product-info/%s
                controller: 'App\Controller\DefaultController::productInfoPage'
                variables: id
                defaults: ''
                siteId: {  }
                methods: {  }
                priority: 1
                creationDate: 1664370681
                modificationDate: 1664370895
